name: 'Build and Deploy'
  
on:
  workflow_dispatch:
  push:
    branches: main
  
jobs:
  Release-Build-and-Deploy: 
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    
    - name: 1. Increment Version
      run: |
        (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/CalvinAllen/devops-scripts/master/gh-actions-set-vsix-version.ps1") | iex
        Vsix-IncrementVersion `
            -BuildNumber ${{ github.run_number }} `
            -manifestFile './src/CodingWithCalvin.OpenBinFolder.Vsix/source.extension.vsixmanifest' `
            -extensionSourceFile './src/CodingWithCalvin.OpenBinFolder.Vsix/source.extension.cs'
      shell: powershell

    - name: 3. Bootstrapping NuGet Installer
      uses: nuget/setup-nuget@v1
    
    - name: 4. Restoring Packages
      run: nuget restore ./src/CodingWithCalvin.OpenBinFolder.sln
    
    - name: 5. Building x64 Project
      run: msbuild './src/CodingWithCalvin.OpenBinFolder.Vsix/CodingWithCalvin.OpenBinFolder.Vsix.csproj' /p:configuration='Release' /p:platform='x64'
        
    - name: 8. Publishing x64 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: '${{ github.workspace }}\src\CodingWithCalvin.OpenBinFolder.Vsix\bin\x64\Release\CodingWithCalvin.OpenBinFolder.Vsix.vsix'
        name: latest-x64
